id: 4
peers: {
  "2":"127.0.0.1:9702",
  "3":"127.0.0.1:9703",
  "1":"127.0.0.1:9701",
  "5":"127.0.0.1:9705",
}
log_level: INFO
listen_sql: 0.0.0.0:9604
listen_raft: 0.0.0.0:9704
data_dir: data
compact_threshold: 0.2
storage_raft: bitcask
storage_sql: bitcask