id: 5
peers: {
  "2":"127.0.0.1:9702",
  "3":"127.0.0.1:9703",
  "4":"127.0.0.1:9704",
  "1":"127.0.0.1:9701",
}
log_level: INFO
listen_sql: 0.0.0.0:9605
listen_raft: 0.0.0.0:9705
data_dir: data
compact_threshold: 0.2
storage_raft: bitcask
storage_sql: bitcask