id: 2
peers: {
  "1":"127.0.0.1:9701",
  "3":"127.0.0.1:9703",
  "4":"127.0.0.1:9704",
  "5":"127.0.0.1:9705",
}
log_level: INFO
listen_sql: 0.0.0.0:9602
listen_raft: 0.0.0.0:9702
data_dir: data
compact_threshold: 0.2
storage_raft: bitcask
storage_sql: bitcask