id: 3
peers: {
  "2":"127.0.0.1:9702",
  "1":"127.0.0.1:9701",
  "4":"127.0.0.1:9704",
  "5":"127.0.0.1:9705",
}
log_level: INFO
listen_sql: 0.0.0.0:9603
listen_raft: 0.0.0.0:9703
data_dir: data
compact_threshold: 0.2
storage_raft: bitcask
storage_sql: bitcask